name: shiko
favicon: null
layout_spectrum: 0.33171235653571784
typography_spectrum: 0.47079208376817405
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6448119301348925
  lightness: 0.6696229064837098
  saturation: 0.08572672354057431
  rhythmicContrast: 0.619124491000548
purpose: []
